export const portfolioConstants = [
  {
    id: 1,
    name: "Ecommerce Website",
    category: "Web Design",
    imagesrc: "/portfolio_images/img-1.jpg",
  },
  {
    id: 2,
    name: "Mobile Banking App",
    category: "Mobile App",
    imagesrc: "/portfolio_images/img-4.jpg",
  },
  {
    id: 3,
    name: "Portfolio Website",
    category: "Web Design",
    imagesrc: "/portfolio_images/img-7.jpg",
  },
  {
    id: 4,
    name: "Social Media App",
    category: "Mobile App",
    imagesrc: "/portfolio_images/img-8.jpg",
  },
  {
    id: 5,
    name: "Travel Blog",
    category: "Web Design",
    imagesrc: "/portfolio_images/img-8.jpg",
  },
  {
    id: 6,
    name: "Fitness App",
    category: "Mobile App",
    imagesrc: "/portfolio_images/img-10.jpg",
  },
  {
    id: 7,
    name: "E-learning Platform",
    category: "Web Design",
    imagesrc: "/portfolio_images/img-1.jpg",
  },
  {
    id: 8,
    name: "Weather App",
    category: "Mobile App",
    imagesrc: "/portfolio_images/img-4.jpg",
  },
  {
    id: 9,
    name: "Portfolio Redesign",
    category: "UI/UX Redesign",
    imagesrc: "/portfolio_images/img-7.jpg",
  },
  {
    id: 10,
    name: "Ecommerce Mobile App",
    category: "Mobile App",
    imagesrc: "/portfolio_images/img-8.jpg",
  },
  {
    id: 11,
    name: "Travel Website",
    category: "Web Design",
    imagesrc: "/portfolio_images/img-9.jpg",
  },
  {
    id: 12,
    name: "Health Tracking App",
    category: "Mobile App",
    imagesrc: "/portfolio_images/img-10.jpg",
  },
  {
    id: 13,
    name: "Corporate Website",
    category: "Web Design",
    imagesrc: "/portfolio_images/img-1.jpg",
  },
  {
    id: 14,
    name: "Recipe App",
    category: "Mobile App",
    imagesrc: "/portfolio_images/img-4.jpg",
  },
  {
    id: 15,
    name: "Dashboard UI",
    category: "UI/UX Redesign",
    imagesrc: "/portfolio_images/img-7.jpg",
  },
  {
    id: 16,
    name: "Food Delivery App",
    category: "Mobile App",
    imagesrc: "/portfolio_images/img-8.jpg",
  },
  {
    id: 17,
    name: "Fashion Ecommerce",
    category: "Web Design",
    imagesrc: "/portfolio_images/img-9.jpg",
  },
  {
    id: 18,
    name: "Fitness Website",
    category: "Web Design",
    imagesrc: "/portfolio_images/img-10.jpg",
  },
  {
    id: 19,
    name: "Task Management App",
    category: "Mobile App",
    imagesrc: "/portfolio_images/img-1.jpg",
  },
  {
    id: 20,
    name: "Blog Redesign",
    category: "UI/UX Redesign",
    imagesrc: "/portfolio_images/img-4.jpg",
  },
];
